ALTER TABLE runs
	ADD COLUMN IF NOT EXISTS verification_started_at TIMESTAMPTZ,
	ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ,
	ADD COLUMN IF NOT EXISTS verification_attempts INTEGER NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS verification_error TEXT;
