ALTER TABLE runs
	ADD COLUMN IF NOT EXISTS review_status TEXT NOT NULL DEFAULT 'unreviewed',
	ADD COLUMN IF NOT EXISTS review_notes TEXT NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
